name: CI
on:
  workflow_dispatch:
    inputs:
      deploy_env:
        type: string
        default: int30
# env:
#   GITHUB_WORKSPACE: /runner/_work/xyz
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          # Your test commands here
          echo "Running tests..."

      - name: Deploy to staging
        if: ${{ inputs.deploy_env }} == 'int30'
        run: |
          # Your deployment steps to staging environment
          echo "Deploying to staging..."

